openanthem/nimbus-core

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/base-control.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/signature.component.ts
nimbus-ui/nimbusui/src/app/services/control-subscribers.service.ts

* Removed signature's underlying ```<img>``` tag and added control for the ```canvas``` element to be the primary display of signature data
* Added control subscriber to monitor enabled property for form controls. Currently only signature.component.ts is subscribing to it in ```ngOnit```
* Refactored ```signature.component.ts``` for code cleanup
* Added Javadocs for ```Signature``` in View Config
* Added documentation to ```signature.component.ts```
The issue was that the underyling ```<canvas>``` HTML element was being removed due to the ```ngIf``` re-rendering when the signature components ```disabled``` property changed. This was causing the existing configurations for the ```<canvas>``` element to be lost after something like ```EnableConditional``` or ```ActivateConditional``` …

NIM-17256: Signature component behaves inconsistently

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/Command.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/CommandElementLinked.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/AbstractCommandExecutor.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/BaseCommandExecutorStrategies.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/ExecutionContext.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorUpdate.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultCommandPathVariableResolver.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultExecutionContextPathVariableResolver.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/ParamCodeValueProvider.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/search/DefaultSearchFunctionHandlerLookup.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/LabelConfigEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/AuditStateChangeHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ConfigConditionalStateChangeHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/AbstractEntityState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultExecutionRuntime.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultExecutionTxnContext.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultListParamState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultModelState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/entity/client/Client.java

Addresses 25 "Bugs" from Sonar.
* The return value of "orElseThrow" must be used.
* L86
* The return value of "orElseThrow" must be used.
* L87
* The return value of "orElseThrow" must be used.
* L88
* The return value of "orElseThrow" must be used.
* L89
* Call "Optional#isPresent()" before accessing the value.
* L204
* Only the sign of the result should be examined.
* L113
* A "NullPointerException" could be thrown; "tree" is nullable here.
* L77
* Call "Optional#isPresent()" before accessing the value.
* L90
* Call "Optional#isPresent()" before accessing the value.
* L83
* This class overrides "equals()" and should therefore also override "hashCode()".
* L78
* Call "Optional#isPresent()" before accessing the value.
** L130
* Call "Optional#isPresent()" before accessing the value.
* L78 …

NIM-17237: Sonar Bug Fixes

---

nimbus-ui/nimbusui/src/app/components/platform/form-element.component.ts
nimbus-ui/nimbusui/src/app/components/platform/validators/ValidationUtils.ts
nimbus-ui/nimbusui/src/app/services/service.constants.ts

* Removed copy/paste if statements and replaced with a lookup of default validation error messages.
* Hard coded defaults have been moved out of `form-element.components.ts` to `service.constants.ts`.
* The hope is that this should make adding new validators on the client side less of a burden and to make the logic more readable.

Form Validation Refactor

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/EvalExprWithCrudDefaults.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValuesConditionalStateEventHandler.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValuesConditionalStateEventHandlerTest.java

Fixed an issue where param values were not coming back when that param was disabled.
Fixes NIM-17698
- Refactored location of disabled handling to allow for the propagation of Values processing
- ValuesConditional still stops the state reset when the associated targetParam is disabled.
The issue was occurring when the response from the server was sending the combobox param's state but not sending the values array. Since in `combobox.component.ts` the `value` is being set, but the `options` is not being set (as `element.values` is not coming back from the server), the underling PrimeNG component is not rendering the saved state on the UI.

NIM-17698: Combobox Issue

---

nimbus-ui/nimbusui/src/app/services/layout.service.ts

Fixes # Called the method to resolve the label for a param
- The global nav menu title will also have the capability to show a label that is configured

label for global nav menu

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/calendar.component.ts

Fixes a regression issue for calendar
- Added two hooks to `emitValueChangedEvent(...)` for `(change)` and `(onSelect)` for the PrimeNG Calendar component.
Functional Testing in Petclinic
N/A

Fixing calendar value change issue

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultCoreBuilderConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultCoreExecutorConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/Action.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/Command.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorGet.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorNav.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorNew.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorProcess.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorSearch.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultCommandExecutorGateway.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/FunctionExecutor.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s11/core/FuncHandlerTestModel.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultBehaviorExecutorStateTest.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/changelog/ChangeLogTest.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/s11/FunctionExecutorTests.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/s11/FunctionHandlerTests.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/s2/S2_ValidateColElemConfigTest.java

Segregate execution of Default Command Executors and Function Handlers. Currently they are co-mingled and causing errors in certain scenarios
Fixes #
1. Renamed AbstractFunctionCommandExecutor to FunctionExecutor. This will no longer be an abstract class and will process all function handlers.
2. Update DefaultAtionExecutorNew, Get, Process, Nav and Search and made them independent of function handler execution
3. Updated DefaultCommandExecutorGateway to delegate all calls to FunctionExecutor once the execution context loads and the command contains a function handler

1.1.0.m2 func handler segregation

---

nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.html
nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.ts

Modal component's close icon is not functioning right. 
- Changed the binding of the visible property to a local property instead of param.visible. The primeNg logic of firing the callback changed and hence the rework on this component and the issue.
UI component refactor to accomodate primeng upgrade

Modal dialog close icon issue

---

nimbus-ui/nimbusui/src/app/directives/display-value.directive.ts
nimbus-ui/nimbusui/src/app/services/service.constants.ts

Change made to display-value directive to handle css class additions for datatypes other than String. 
NIM-19190
- Remove the blanket displayValue.trim() which causes error if display value is not of type string
- Do a type check before adding the value to the element class
Functional Testing

ApplyStyles Bugfix for boolean values: Handling datatypes other than string for applying styles

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/MessageConditional.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/MessageConditionalHandler.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/VPSampleViewPageAqua.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/MessageConditionalEventHandlerTest.java
nimbus-ui/nimbusui/src/app/shared/param-utils.ts

When there are interdependent conditions written on message conditionals, there needs to be a way through which messages can be re-evaluated on a parameter where state change has not occurred. 
Fixes # 18085
- Introduced targetpath on messageconditional so that messages of a different parameter can be set.
Junit

Support for targetPath in message conditional

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultFrameworkExtensionsConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/StyleConditional.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/StyleConditionals.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/EntityState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/StateHolder.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/StyleConditionalStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultParamState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/support/DefaultJsonParamSerializer.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/domain/mock/MockParam.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/domain/support/utils/ParamUtils.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/VPSampleViewPageAqua.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultBehaviorExecutorStateTest.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/StyleConditionalStateEventHandlerTest.java
nimbus-ui/nimbusui/src/app/components/platform/form-builder.service.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/grid.component.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.html
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.ts
nimbus-ui/nimbusui/src/app/services/page.service.ts
nimbus-ui/nimbusui/src/app/shared/param-state.ts

Adding `@StyleConditional` and UI Support for it. See the following example:
**Sample Config**
```java
// Assume state of nickname is: "Bob"
@GridColumn
@Path
private String nickname;
@GridColumn(hidden = true)
@Path
@StyleConditional(targetPath = "/../nickname", condition = {
@StyleConditional.Condition(when = "state == true", then = @Style(cssClass = "preferred"))
})
private boolean shouldUseNickname;
```
**Rendered HTML**
If `shouldUseNickname` is `true` then:
```xml
<span title="Bob" class="ng-star-inserted">
<span class="fieldValue nickname preferred">Bob</span>
</span>
```
If `shouldUseNickname` is `false` then:
```xml
<span title="Bob" class="ng-star-inserted">
<span class="fieldValue nickname ">Bob</span>
</span>
```
- Introduced `gridData` to the UI param state.
- Refactored …

NIM-17212: Adding StyleConditional and UI Support for GridColumn

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/MappedDefaultListParamState.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s13/core/S13Core.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s13/view/S13SampleLineItem.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s13/view/S13View.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/s13/CollectionsStateRetrievalTest.java

Fixed an isolated issue where a core param's (collection) instantiation was not correctly updating the associated view param's leaf state.
See more details in **Additional Notes** below.
- Added test case for bug.
- Added fix.
This addresses NIM-17467, a bug where invoking a `_get` call on a param that looks like the following:
```java
@MapsTo.Path(linked = false)
@Config(url = ".m/_process?fn=_set&url=/p/s13_core/_search?fn=query&where=s13_core.attr_int.eq(42)")
private List grid;
```
and given the result of the framework call `/p/s13_core/_search?fn=query&where=s13_core.attr_int.eq(42)` is returning something like:
```json
[{
"attr_String": "I'm the first!",
"attr_int": 42,
}, {
"attr_String": "I'm the second!",
"attr_int": 42,
}]
```
then the returned leafState of the collection was …

NIM-17467: Fixing collection instantiation issue

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValuesConditionalStateEventHandler.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/core/SampleCoreValuesEntity.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValuesConditionalStateEventHandlerIntegTest.java

Fixed an issue where non-string types were not working in `@ValuesConditional`
N/A
- ValuesConditionalStateEventHandlerIntegTest#t11_nonStringState()
N/A

Support for @ValuesConditional and non-string types

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorUpdate.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/core/SampleCoreEntity.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/VRSampleViewRootEntity.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorUpdateTest.java

Fixed an issue where `_update` was setting the state instead of adding for a collection containing a non-nested type.
Parsing collections now takes priority over leaf state parsing (this was the previous behavior back [before it was broken](https://github.com/lopezton-anthem/nimbus-core/commit/1036874c8ed4217a83f193f2dbe38046a0551843#diff-ac63c7ab314e5f56d2f3ee26bb92a817))
See `DefaultActionExecutorUpdateTest#t12_update_collection_simple()`
It looks like this was introduced back in `1.1.0.M1-SNAPSHOT`.

_update fix for collections

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.html
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

- Deprecated `dataKey` attribute of `@Grid`
- The `dataKey` attribute may be removed in the future. Marked it as deprecated for now.
- The `@Grid` template now uses the server-generated `elemId` value instead of the default `id` or a configured `dataKey` to expand `@GridRowBody` content within a collection element
- Functional Testing in Petclinic
- Existing implementations that generated an `datakey` for nested collections can remove these implementations.

Deprecating @Grid dataKey Attribute

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorGet.java

Reverting exception throw on _get call without refId
Reverted a change from 4b3026924aacade2526d89848dee59e393408986
N/A
Fixes an application build

Reverting exception throw on _get call without refId

---

nimbus-ui/nimbusui/src/app/components/platform/link.component.ts

- Fixed an issue where using `@Link` was giving a UI console error when used with `external` and a link key/value replacement
- Change to `link.component.ts`
- Functional Testing in client application
N/A

Null safety check

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultCoreConfiguration.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/search/DefaultSearchFunctionHandlerLookup.java

Hi @jayantchaudhuri, per our discussion checking in the change to cache the static code value lookup calls see if it helps with performance. if perf shows improvement, we can discuss and optimize the caching settings/impl.

Enable caching for staticcodevalue dao search

---

nimbus-ui/nimbusui/src/app/components/platform/header/header-global.component.html
nimbus-ui/nimbusui/src/app/components/platform/header/header-global.component.ts
nimbus-ui/nimbusui/src/app/services/page.service.ts

- Fixed unneccesary browser console error logging
- If `imgSrc` of a `@Link` is not provided on `@PageHeader(Property.LOGO)` decorated field, the header logo will no longer be displayed
- Minor console error logging changes
- Removed throw statements from `page.service.ts`
Functional Testing in Petclinic
N/A

NIM-19919 & 19922

---

nimbus-core/lombok.config

After spring boot upgrade, there was an JSON parse error when using GenericExecute. Based on lombok's release notes -  v1.16.20 requires a new property to generate @ConstructorProperties
https://github.com/rzwitserloot/lombok/issues/1563
https://projectlombok.org/changelog (v1.16.20 (January 9th, 2018))
JSON parse error: Cannot construct instance of `com.antheminc.oss.nimbus.domain.cmd.exec.ExecuteOutput$BehaviorExecute` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator); nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.antheminc.oss.nimbus.domain.cmd.exec.ExecuteOutput$BehaviorExecute` (no Creators, like default construct, exist): cannot deserialize …

lombok v1.16.20 requires a new property to generate @ConstructorProperties

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/EntityState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/StateHolder.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultListParamState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultParamState.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/domain/mock/MockParam.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/SampleParamStateHolders.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/VRSampleViewRootEntity.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/ParamStateHolderTests.java

- Added `isEmpty()` for `Param` implemenetations
- Behavior for invoking `isEmpty` on the following parameter types is as follows:
- **Collection**: returns `true` if the collection's nested params is `null` or its size is <= 0
- **String**: returns `true` if the string is `null` or the length of the string is `0`
- **Anything else**: returns `true` if the state is `null`
See `com.antheminc.oss.nimbus.domain.model.state.ParamStateHolderTests`
N/A

Adding isEmpty() for Param

---

nimbus-ui/nimbusui/src/app/directives/display-value.directive.ts

- Fixed an issue where using `applyValueStyles` in `@GridColumn` for the value of `On Hold` was nonfunctional
- Modified `display-value.directive.ts` to use `typeof` instead of `instaceof String`
- Functional testing in Pet Clinic application
There was an issue where using `applyValueStyles` in `@GridColumn` for the value of `On Hold` was delivering the following browser error:
```
{"stack":"Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('On Hold') contains HTML space characters, which are not valid in tokens.
at e.addClass (http://localhost:8080/petclinic/main.83110ba23dbc1f916935.js:1:1087728)
at e.addClass (http://localhost:8080/petclinic/main.83110ba23dbc1f916935.js:1:2339959)
at e.ngOnChanges (http://localhost:8080/petclinic/main.83110ba23dbc1f916935.js:1:198201 …
```

Fixes applyValueStyles space replacement issue

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/header-checkbox.component.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

Providing support for multi-select header checkbox to select all records in the dataset (including all pages in a paginated datatable) and also retain the individual record selection across pages. 
Adding a new attribute `headerCheckboxToggleAllPages` in `@Grid` annotation. By default this is set to false. The behavior for the attribute is as follows:
- When set to true - when a user checks the select-all checkbox in the header, all the rows in the dataset across all pages are selected. Also, individual selection of records will be retained as user moves from page to page.
- When set to false - when a user checks the select-all checkbox in the header, all the rows in the current page are selected. (current default implementation)
N/A

Grid multi-select header checkbox to select all records in dataset based on`headerCheckboxToggleAllPages` attribute in @Grid

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/header-checkbox.component.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts

Bugfix for grid filter on multi-select checkbox to select only filtered values instead of all values. Previously, when a grid data is filtered using table filter and the filtered records are selected using multi-select checkbox, all the records in the grid were being selected. 
Original PR details:
https://github.com/openanthem/nimbus-core/pull/303
Uncheck all the checked rows onFilter event - this is to prevent keeping
old rows that may not be on current page checked based on current filter
criteria. Also will prevent them from being submitted on post event.
Cherry-pick commits:
f938f47f86b29e9fb1b91d99b646ebfe80ddaef5
2e93d2cd8f6e07ea1e4f804abe4099f57e31f5fc
4e6f5caa04e7522089f8f4f943c35ef31bbe91d7 from original PR 
https://github.com/openanthem/nimbus-core/pull/303
[ ] Bug fix
N/A
N/A

Grid filter multi-select bugfix 

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/header-checkbox.component.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

Providing support for multi-select header checkbox to select all records in the dataset (including all pages in a paginated datatable) and also retain the individual record selection across pages.
Merging original PR for 1.2.x to 1.1.11 
https://github.com/openanthem/nimbus-core/pull/322
Please see https://github.com/openanthem/nimbus-core/pull/322 for details
N/A

Grid multi-select to select all records in dataset based on`headerCheckboxToggleAllPages` attribute in @Grid

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java

Adding the missing `dataEntryField` attribute to `@MultiSelect` viewconfig annotation, which is preventing the MultiSelect component from rendering in a form.
N/A

Missing dataEntryField attribute to MultiSelect component

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/action-dropdown.component.mockdata.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/action-dropdown.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/action-dropdown.component.ts

- `@Link` components within `@LinkMenu` now support framework configurations that set the `visible` property (e.g.  `@VisibleConditional`)
- Added boolean logic to render/unrender the `@Link` within `@LinkMenu`
- Reformatted the HTML Template for readability
- Added template test cases and `action-dropdown.mockdata.ts` for testing
- See `action-dropdown.component.spec.ts`
- Functional testing in petclinic
N/A

NIM-20937: Action Dropdown to support Visible flag

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/support/DefaultJsonParamSerializer.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/VPSampleViewPageAqua.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/MessageEventHandlerTest.java
nimbus-test/src/test/resources/p9_message_onload.drl

Reset messages on param once the json response has been created, such that message state is not retained in the param by the server side. This ensures that when a message is set on a param, the message does not get displayed on UI every time a user navigates to the page where the param has the message.
Setting messages on param to null in DefaultJsonParamSerializer.
MessageEventHandlerTest.java
TODO : Scenarios where further conditional processing is done based on the message text needs to be addressed, since the message state has been reset. There will be a sync issue until a state is reloaded and message is set.

Reset Message state in JSONSerialization

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/CommandBuilder.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultCommandPathVariableResolver.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/crossdomainresolver/view/VRSampleCrossDomain.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/crossdomainresolver/view/VRSampleMultiDomain.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/crossdomainresolver/CrossDomainPathResolverTest.java

NIMBUS-2 : Capability for DomainPathResolver to resolve cross domain paths.
NIMBUS-2 : Added a check in DefaultCommandPathVariableResolver to resolve cross domain paths.
Ex: `@Config(url="/attr3/_replace?rawPayload=\"<!/p/sample_crossdomain_pathresolver/nested/attr_1!>\"")`
N/A
N/A
CrossDomainPathResolverTest.java
N/A

NIMBUS-2:: Cross domain path variable resolver

---

nimbus-ui/nimbusui/src/app/components/platform/section.component.html

Conditionally binding visible attribute to the parent div.
N/A
N/A
N/A
N/A

NIMBUS-89:: visible conditional for parent div

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/db/MongoSearchByQuery.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/builder/DefaultActionExecutorSearchTest.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/chart/SampleChartDataSetTest.java

The regex was not checking for if the aggregate word had been escaped. e.g \"aggregate\". This change fixes it.

NIMBUS-96:: Updates the regex for aggregate query match

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/rich-text.component.ts

* Includes support for `@RichText` for `readonly` mode
* Added `readonly` as an attribute
* `@RichText` now supports the following scenarios:
* Editable and Enabled
* Editable and Disabled (displays the toolbar but is non-functional, e.g. user can not input)
* Readonly and Enabled (effectively just a readonly field, but is not marked as form disabled)
* Readonly and Disabled
N/A
N/A

NIMBUS-10:: RichText Component (readonly support)

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/CommandBuilder.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultCommandPathVariableResolver.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/crossdomainresolver/view/VRSampleCrossDomain.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/crossdomainresolver/view/VRSampleMultiDomain.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/crossdomainresolver/CrossDomainPathResolverTest.java
pom.xml

Capability for DomainPathResolver to resolve cross domain paths.
Creating PR for 1.1.x branch with additional test cases (cross domain with refID).
Original PR to 1.1.11: https://github.com/openanthem/nimbus-core/pull/338
NIMBUS-2 : Added a check in DefaultCommandPathVariableResolver to resolve cross domain paths.
Ex: `@Config(url="/attr3/_replace?rawPayload=\"<!/p/sample_crossdomain_pathresolver/nested/attr_1!>\"")`
`@Config(url="/attr9/_replace?rawPayload=<!json(/p/sample_core:<!/../attr9_id!>)!>")`
- Testcase update
CrossDomainPathResolverTest.java

NIMBUS-2:: Additional test cases - DomainPathResolver to resolve cross domain paths 

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/button.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/event-propagation.directive.ts

Submit button was not getting disabled if the form was invalid during re-entry of the same form.
EventPropagationDirective now has the validity check if the form is valid in case of submit buttons.
N/A

NIMBUS-103:: fix for submit buttons disabled property on form re-entry

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/rich-text.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/rich-text.component.ts
nimbus-ui/nimbusui/src/app/mockdata/rich-text.component.mockdata.spec.ts

* `@RichText`
* Added support for `ToolbarFeature.VALUES_COMBOBOX`
* Adds a combobox to the toolbar. Selected values from the combobox will be inserted:
* into the editor's last known cursor position (at the start if untouched)
* into the editor's previous highlighted text
* Values can be supplied by decorating the field with `@Values`.
* Functional testing in Pet Clinic
* See `rich-text.component.spec.ts`
N/A

NIMBUS-64:: Rich Text Values Dropdown

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValuesConditionalStateEventHandler.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/core/SampleCoreValuesEntity.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValuesConditionalStateEventHandlerIntegTest.java

Param state was being reset when the dataType is String[] as there was code that was assuming that state is always string.
Changed the logic to run for only string datatypes as for array list we might have to run through the scenarios and see If we want to do the same as well. If so, will create a separate feature and PR for it.
added test case t12_arrayState in the ValuesConditionalStateEventHandlerIntegTest class to depict this scenario.

NIMBUS::103 fix to address state being reset using valuesconditional

---

nimbus-ui/nimbusui/src/app/components/platform/content/tab.component.ts

There is a known issue with primeNG when dynamically creating tab panels.  Per their documentation we should have the selected property to avoid improper behavior.
N/A
N/A
N/A
N/A

NIMBUS-101:: selected attribute for tab component

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/ParamStateGateway.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/ParamStateRepositoryGateway.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/support/PrimitiveUtils.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/core/SampleCoreEntity.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/VPSampleViewPageGreen.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/ActivateConditionalNoConversionTest.java

* Fixes #393
* Fixes an issue where using an `@ActivateConditional` that targets a nested parameter having mapped children parameters would not reset the state of the children.
* Adds a condition for invoking `setState` on all mapped children living under a view param when that view param's `setState` is invoked
* See `ActivateConditionalNoConversionTest#testUnmappedNestedParamWithMappedChildren()`
N/A

NIMBUS-121:: setState fix for unmapped nested entities with mapped children

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/process/URLBasedAssignmentFunctionHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/Constants.java

* Fixed an issue where calling a `URLBasedFunctionHandler` with `url` starting with a domain alias like: `"/petclinic"` was inappropriately doing a cross domain fetch.
* Replaced external check from`"/p"` to `"/p/"`
* Minor code cleanup
TODO
N/A

URL Based Function Handler Fix for "p" alias calls

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/CommandExecution.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/domain/support/pageobject/UnitTestPage.java

* Added changes for test support
* Added helper methods for test support
* `MultiOutput#findFirstParamOutputEndingWithPath(String path)`
* `MultiOutput#findParamOutputsEndingWithPath(String path)`
* Modified `ParamUtils#convertToStringPayload(Object payload)` to transform `String` types to their JSON equivalent. (e.g. the string `foo` should be transformed to `"foo"`)
* Used in petclinic, will add a test case for this in framework later.
Introduced `findParamOutputsEndingWithPath(String path)` method to `MultiOutput` to help avoid brittle test cases where the `refId` was being retrieved in test cases by using either `getSingleResult()` or `getOutputs.get(HARD_CODED_INDEX)`.
**Sample Code Snippet:**
```java
Holder<MultiOutput> response = (Holder<MultiOutput>) …
```

Test support

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/MessageConditional.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/EntityState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/MessageConditionalHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/support/DefaultJsonParamSerializer.java
nimbus-ui/nimbusui/src/app/components/platform/base-element.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form-element.component.ts
nimbus-ui/nimbusui/src/app/shared/message.ts

* Added `isTransient` attribute to `MessageConditional` to support messages that are retained between successive serverside and UI requests
See above
Existing test cases
N/A

NIMBUS-140:: Adding non-transient ability for messages

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorGet.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultExecutionContextLoader.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/db/ParamStateAtomicPersistenceEventListener.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s14/core/StChangeOnStLoadCore.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s14/view/StChangeOnStLoadModel.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/s14/StateChangeOnStateLoadTest.java

When we have a OnStateLoad event on a parameter that triggers a State Change event on any other parameter in the same root domain, it gives a stack overflow error. In the current code, the quad model gets cached in the session after the state load event is triggered. If the state load event triggers a state change event on the same root domain, then framework does not find the quad model in cache and tries to instantiate the model and the cycle continues. 
Change has been made to execute the initState() method only after the quad model is cached
Bug fix
StateChangeOnStateLoadTest
There might be a need to re-evaluate how to sequence event execution. The change above will resolve entities that are cached. For the entities that are not cached, the stack overflow issue would still continue

NIMBUS-137: StackOverflow Error when a OnStateLoad event triggers a state change handler

---

nimbus-ui/nimbusui/src/app/services/httpclient-interceptor.service.ts
nimbus-ui/nimbusui/src/app/services/service.constants.ts
nimbus-ui/nimbusui/src/app/shared/app-config.interface.ts

Ability to configure an error page for certain use cases when server fails
Ui would call /apperror endpoint when there is an error when config gets returns to UI when app url is hit for the first time.

NIMBUS-164:: call error endpoint for usecases like db is down

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultFrameworkExtensionsConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/GridStateLoadHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/LabelStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/EntityState.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/labelstate/view/Sample_View_Label_Entity.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/LabelStateOnLoadEventHandlerTest.java

* Fixes an issue where configuring a `@Grid` without a `@Label` results in the title row of the grid not rendering labels
Considering the logic for `elemLabels` is only needed for `@Grid` params and not all collection params, I've refactored `LabelStateEventHandler` logic into `GridStateLoadHandler`
*`LabelStateOnLoadEventHandlerTest`
* testCollectionElemLabels`
N/A

NIMBUS-51: Display Labels when not decorated with @Label

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/db/ParamStateAtomicPersistenceEventListener.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/repo/core/SampleRepoDifferentAlias.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/repo/db/ParamStateAtomicPersistenceEventListenerTest.java

Fixes #459 
* Fixed an isolated issue in 1.3 versions where a domain entity was ALWAYS being persisted under the `@Domain` alias, instead of the `@Repo` alias. This issue was introduced with a previous merge of the repo changes from 2.0.x.
* Added logic for Mongo persistence where `@Repo` is checked first and used. This code was missed during a merge.
* `ParamStateAtomicPersistenceEventListenerTest`
* `testDomainRepoAliasMismatchPersistence()`
N/A

NIMBUS-182: repo alias persistence fix

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/support/JustLogit.java

Encoding logs as attackers could inject malicious content using tags like '<'.   This could be dangerous if the logs are integrated and viewed using a website in a browser where javascript can run.
Encoding is little bit relaxed for certain symbols as we use them a lot while logging. (But definitely not '<' and '>' tags)
Eg:   arg[0]: Command(absoluteUri=/test/test/p/test/_new, clientUserId=null, action=_new, behaviors=[$execute])

NIMBUS-163  log encoding (veracode vulnerability)

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorNav.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/nav/PageNavigationResponse.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/Constants.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorNavTest.java
nimbus-ui/nimbusui/src/app/services/page.service.ts
nimbus-ui/nimbusui/src/app/shared/page-navigation-response.ts

Fixes #465 
Added configuration and UI support for navigating to external web pages using `@Config` and the default  `_nav` action executor.  See the following config:
```java
@Label("Nav Externally")
@Link
@Config(url = "/_nav?redirectUrl=https://mywebsite.com")
private String navExternally;
```
* `DefaultActionExecutorNav` Changes
* Modified to accept query param `redirectUrl` as a URL string
* Refactored the resulting object returned and received from `String` to `PageNavigationResponse`
* The UI framework now responds more intelligently to the `PageNavigationResponse` response received from the server
* `DefaultActionExecutorNavTest`
This change does not replace the existing `@Link(value = Type.EXTERNAL, target = "_blank", url = "url")` typed configuration. Rather it offers a new …

NIMBUS-187: external link nav via config

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java

Removes deprecations and adds documentation for using the `@Grid` multiple row selection feature.
See https://github.com/openanthem/nimbus-docs/pull/65
N/A
N/A
N/A
N/A

NIMBUS-208

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/combobox.component.ts
nimbus-ui/nimbusui/src/app/pipes/select-item.pipe.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

Added support for `@ComboBox` attribute `defaultLabel` which provides the ability to add a default selection item to the top of the rendered combo box.
Fixes #481 
* Modified `SelectItemPipe` to take an optional `Param` argument to determine additional details about what should be added to the selection items.
N/A
N/A

NIMBUS-206: @ComboBox defaultLabel

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/channel/web/WebActionControllerAdvice.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorGet.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/FunctionExecutor.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/config/builder/DomainConfigBuilder.java

Adds more user-friendly exception message information for commonly experienced exceptions
* Exception message improvements
* Command DSL Reference to an undefined function handler
* See `FunctionExecutor.handleUnknownFunctionHandler`
* Command DSL invocation of `_get` call on an entity that does not exist now gives `"Entity not found for /object:42"` instead of `"Both view and core can not be null"`
* See `DefaultActionExecutorGet.createNewQuad`
* Command DSL execution of an unknown domain alias offers suggestions for common errors. 
* Ran sort members/formatter on classes that were touched
* Added a `null` check for when `application.exceptions` in `application.yml` is empty, to prevent a `NullPointerException` in the global exception handler.
N/A
N/A

Exception message enhancements

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorGet.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/ws/DefaultWSModelRepository.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/repo/ModelRepositoryTest.java

Fixed an issue where `_get` on an external webservice domain was not working properly.
* Added a provision to allow `_get` requests without a `refId` for entities where `@Repo(Database.rep_ws)` is present.
* Added a warning when `refId` is sent, as it doesn't really make sense.
* Modified the external `_get` retrieval URL.
* Previously a request to an external domain entity `"ext_client"` like `"/a/b/p/ext_client/foo/_get"` configured to point to: `"http://coolwebservice.com/api"` would invoke a webservice call via the url: `"http://coolwebservice.com/api/a/b/p/ext_client/foo/_get"`. Now, the same call invokes via `"http://coolwebservice.com/api"`
* `ModelRepositoryTest`
N/A

External Model Repository fix for _get

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/combobox.component.ts

ComboBox is missing a required icon because the class has a new ngOnInit() method added recently
called the super.ngOnInit()

combobox req icon missing on load

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/search/DefaultSearchFunctionHandlerLookup.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/VPSampleViewPageGreen.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorSearchHttpTest.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/combobox.component.ts

Fixes #515 
Fixes an issue where `@ComboBox` was not retaining the value and the Search by Lookup function handler was assuming `code` needed to be treated as `String`.
See .java testcases
N/A

NIMBUS-228: combobox/lookup search fh fix

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/BPMEngineConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/bpm/activiti/ActivitiBPMGateway.java

Current version of the framework reads active task for an entity from the ProcessFlow instance. This runs into synch issue when a workflow is triggered asynchronously. Activiti commits  transaction once the request in processed. Before the transaction is committed, if another thread tries to execute the workflow then it can get incorrect value of the active tasks from ProcessFlow Instance.
Change has been done in ActivitiBPMGateway to always read active tasks from the database
N/A
- [ X] Bug fix
BPMGatewayTests

NIMBUS-135: Active Task Synch Issue

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/services/layout.service.ts

Adds javadocs for `@PageHeader`.
Associated documentation: https://github.com/openanthem/nimbus-docs/pull/67
* javadocs
None
N/A

NIMBUS-159: PageHeader documentation

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/checkbox.component.ts

Fixes #539 
Fixes an issue where `@ComboBox` was displaying the required asterisk when combined with `@NotNull`
DOM change.
N/A
N/A

NIMBUS-244: @Checkbox + @NotNull required fix

---

nimbus-ui/nimbusui/src/app/components/platform/form-builder.service.ts
nimbus-ui/nimbusui/src/app/components/platform/form-element.component.html
nimbus-ui/nimbusui/src/app/components/platform/form-element.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/picklist.component.ts
nimbus-ui/nimbusui/src/app/shared/param-state.ts
nimbus-ui/nimbusui/src/app/shared/param-utils.ts

Fixes #564 
* Refactored the `@Picklist` typescript logic to be cleaner, more concise.
* `sourceList` and `targetList` were incorrectly storing `string[]` in `onInit()`, instead of `Values[]`. This has been corrected and fixes the filter functionality.
* the `leafState` from the server is converted to `Values` on the client side and converted back to `string[]` before being sent to the server.
* If `@Values` are not set for `@PickList` or `@PickListSelected`, and an existing state exists, the plain value of the state will be shown (previously was an empty string). Ideally, `@Values` should always be set.
N/A

NIMBUS-265: @PickList fix for filter

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultProcessConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/process/FilterFunctionHandler.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/VRSampleViewRootEntity.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/process/FilterFunctionHandlerTest.java

Adding a Filter function handler for collection/array typed parameters.
```java
@Domain(value = "sample_view", includeListeners={ ListenerType.websocket })
@MapsTo.Type(SampleCoreEntity.class)
@Repo(Database.rep_none)
@Getter @Setter
public class VRSampleViewRootEntity {
private String[] arr;
private List<String> simple_list;
private List<ComplexObject> complex_list;
@Config(url = "/arr/_process?fn=_filter&expr=contains('pickme')")
@Config(url = "/simple_list/_process?fn=_filter&expr=contains('pickme')")
@Config(url = "/complex_list/_process?fn=_filter&expr=state.p1.contains('pickme')")
private String action_demoFilter;
@Model 
@Data 
public static class ComplexObject {
private String p1;
}
}
```
The expected SpEL predicate syntax is slightly different when the action parameter's …

Function Handler: Filter

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/Constants.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/Model.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/DefaultParamValuesHandler.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/VPSampleViewPageGreen.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/DefaultParamValuesHandlerTest.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValuesConditionalStateEventHandlerTest.java

Fixes #566 
* Invokes the `staticCodeValues` cache prior to `@Config` execution
* Introduced new constants
N/A
N/A

NIMBUS-268: ParamValues Cache

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/LabelConditional.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/StyleConditional.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/ValuesConditional.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/AbstractConditionalStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/AbstractEventHandlerSupport.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ActivateConditionalStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ConfigConditionalStateChangeHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/EnableConditionalStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/EvalExprWithCrudActions.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/EvalExprWithCrudDefaults.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ExpressionConditionalStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/LabelConditionalStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/MessageConditionalHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/RuleStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ScriptEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/StyleConditionalStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValidateConditionalStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValuesConditionalStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/VisibleConditionalStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/conditionals/AssignThenToTargetCaseConditionalHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/conditionals/BooleanSetterConditionalHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/conditionals/IfElseConditionalStateEventHandler.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValuesConditionalStateEventHandlerTest.java

Refactored the conditional annotation support classes for cleaner code and better extensible support.
* `@LabelConditional`, `@StyleConditional`, `@ValuesConditional` now accept `targetPath` as a `String[]` (previously was `String`).
* Deprecated `EvalExprWithCrudActions` and `EvalExprWithCrudDefaults`
* Introduced new core conditional state event handler support classes
* `IfElseConditionalStateEventHandler`
* `AssignThenToTargetCaseConditionalHandler`
* Minor support changes
* Added trace logging to monitor evaluation logic for `com.antheminc.oss.nimbus.domain.model.state.extension` classes.
* Enhanced error messages
* Fixed an issue where `ParamStateHolder` was being wrapped around a `Param` more than once in some annotation handlers.
Conditional test cases
N/A

Conditional annotation refactor

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/ParamCodeValueProvider.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/search/DefaultSearchFunctionHandlerLookup.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/ParamCodeValueProviderUnitTest.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/builder/DefaultActionExecutorSearchTest.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/DefaultParamValuesHandlerTest.java

Supplemental change for #566. Fixes test case failure introduced from #569
* Skips cache retrieval for `null` entries in the `staticCodeValue` cache abstraction
* Polish (`"staticCodeValue"` constant replacements) 
* `DefaultParamValuesHandlerTest`
N/A

NIMBUS-273: fix staticCodeValue caching issue

---

nimbus-ui/nimbusui/src/app/components/platform/fileupload/file-upload.component.ts

Fixes #572 
Reset the files that are temporarily added(upload not yet clicked) when visibility of the fileupload component changes.
Invoked the clear() method to reset the files when server sends an update to the fileupload parameter.

NIMBUS-275: clear files on changes to fileupload

---

nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/components/platform/loader/loader.component.ts
nimbus-ui/nimbusui/src/app/services/loader.service.ts
nimbus-ui/nimbusui/src/app/services/page.service.ts

Button not getting enabled after click as the propagation event is not emitted
Refactored the grid to have a seperate observable to handle spinner event and button event will have as seperate observable to handler global spinner event.

NIMBUS-281:: button even propagation not enabled

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/button.component.ts

Related to #585 and #591
Fixes an issue where clicking a submit button that submits a form that has already had it's `Date` transformed into a `string` was inappropriately trying to transform the date again.

NIMBUS-280: fix for button submit error

---

pom.xml

Fixes an issue where the build would fail to publish javadocs due to the issue outlined here:
https://stackoverflow.com/questions/27808734/jdk8-error-class-file-for-javax-interceptor-interceptorbinding-not-found-whe/47889602
Dependency addition.
run the build
```bash
mvn clean install -DskipTests -P cicdbuild
```
N/A

build fix for javadocs @Transactional issue

---

nimbus-ui/nimbusui/package.json
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts

Primeng upgrade to 7.1.1 to fix grid edit issue
When the grid is empty and add button clicked there is a nullpointer which is fixed with this.

primeng 7.1.1 + grid edit fix

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultCommandExecutorGateway.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultListParamState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultParamState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultStateEventDelegator.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/MappedDefaultListParamState.java

Fixes #531 
* Added deregisterConsumer for mappedParams onDelete
N/A
Commits were previously added directly into support branch. They have been reverted and added back for the sake of the release notes.

NIMBUS-241: Nested collection blank rows fix

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/Model.java

Adds `@TransientParam` for decorative purposes.
N/A
N/A
Gives a way for users to decorate a field to denote that its pure purpose is to be used as a transient variable within the framework.
```java
@TransientParam
private Boolean isValidDate;
@TransientParam
private String action_submit;
@Label(value = "Add")
@Config(url = "<!#this!>/../isValidDate/_process?fn=_set&value=false") 
@Config(when = "findStateByPath('/../../startDate') != null && !findStateByPath('/../../startDate').isBefore(T(java.time.LocalDate).now())", url = "<!#this!>/../isValidDate/_process?fn=_set&value=true")
@Config(when = "!findStateByPath('/../isValidDate')", url = "<!#this!>/../../../../confirmModal/_process?fn=_setByRule&rule=rules/togglemodal")
@Config(when = "findStateByPath('/../isValidDate')", url = …
```

Adding @TransientParam

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/CommandExecution.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/repo/rdbms/core/AddressJPACoreEntity.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/repo/rdbms/core/PersonJPACoreEntity.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/repo/rdbms/core/SampleJPARootCoreEntity.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/repo/rdbms/view/PersonLineItem.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/repo/rdbms/view/VRSampleJPARootViewEntity.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/repo/db/rdbms/DefaultJPAModelRepositoryTest.java
nimbus-test/src/test/resources/application-rdbms-test.yml

Testing for RDBMS implementation
* Refactoring existing test case to be reusable
* Modified `CommandExecution` `findFirstParamOutputEndingWithPath` to return generic type
* Added a QueryDSL specific test class
N/A
N/A

NIMBUS-269: Relational DB Testing

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/EntityConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/ParamConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/builder/internal/AbstractEntityConfigBuilder.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/internal/DefaultModelConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/internal/DefaultParamConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/db/ParamStateAtomicPersistenceEventListener.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/domain/mock/MockParamConfig.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/core/InnerTestModel.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/core/SecondLevelNestedModel.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/core/TestModel.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/VRTestModel.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorUpdateTest.java

When a model attribute is marked @Transient the audit fields should not get updated.
Added an attribute to ParamConfig to hold transient information

NIMBUS-298 :: Transient param persistance fix

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/Notification.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/StateHolder.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/AuditViewHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultParamState.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/domain/mock/MockParam.java

De-registration of mapped audit view entities from core param, post audit entry within AuditViewHandler.
Changes made in AuditViewHandler

De-registration of mapped audit view entities from core param

---

nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts

Clearing grid results with a user action when the page!=1 is causing incorrect grid header
Added condition based on total records

NIMBUS-390 :: update rowstart condition

---

nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts

clearing a grid throws an error and eventually unsubscribes the event updates
Added a condition to expand only when there are grid results
N/A

condition for nested grid expand

---

nimbus-ui/nimbusui/src/app/components/platform/fileupload/file-upload.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/base-control.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/checkbox-group.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/multi-select-card.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/picklist.component.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.ts

Form controls were not participating in the validations when recreated
formControl.enable() called explicitly

NIMBUS-696 :: enable controls when recreated
