openanthem/nimbus-core

README.md

Commiting locally

---

nimbus-ui/nimbusui/package.json

AOT isn't woriking

---

README.md

Include badges for build process and plans.

Badge Updates

---

README.md

E2E Testing

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/picklist.component.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

Configurable Picklist controls (default hidden)

Configurable picklist controls

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java

* Added Javadocs so consumers understand the support for datePattern.
* Ran formatting tool on ViewConfig
The usage of the `datePattern` attribute was not clearly understood by consumers of the Framework.
Documentation.

NIM-17211: Format on Every Date Field

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/WebConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/channel/web/WebActionController.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/Action.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/CommandElement.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/CommandElementLinked.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/internal/DefaultValidatorProvider.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/builder/internal/DefaultQuadModelBuilder.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/AbstractValuesConditionalStateEventHandler.java

Addresses 5 "Vulnerabilities" from Sonar.
* Make this member "protected".
* L53
* Make this member "protected".
* L66
* Make this "public static factory" field final
* L30
* Make factory a static final constant or non-public and provide accessors if needed.
* L30
* Make restTemplate a static final constant or non-public and provide accessors if needed.
* L72

NIM-17263: Fix Security Vulnerabilities

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/MessageConditional.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/EntityState.java
nimbus-ui/nimbusui/src/app/app.module.ts
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.html
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.ts
nimbus-ui/nimbusui/src/app/components/platform/fileupload/file-upload.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form-element.component.ts
nimbus-ui/nimbusui/src/app/components/platform/message/message.component.ts
nimbus-ui/nimbusui/src/app/shared/message.ts
nimbus-ui/nimbusui/src/app/shared/param-annotations.enum.ts

Please review the following changes.

Upgraded Growl Component

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/EntityState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/StateHolder.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultParamState.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/domain/mock/MockParam.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/domain/support/utils/ParamUtils.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/LabelConditionalStateEventHandlerTest.java

Adding getDefaultLabel() and getLabel(String locale) for convienience
- Adding getDefaultLabel() and getLabel(String locale) to `DefaultParamState`
All Tests.
Needed for upgrade to 1.1.0.M2 for downstream applications

Label Convenience methods

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java

Updated the java doc for the scriptName() in the signature component. 
Please review the changes.

Updated the signature javadoc

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/AbstractConfigEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/LabelStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/internal/DefaultEventHandlerConfig.java

Fixing issues identified during 1.1.0.M2 upgrade process with an application
- Removed unused Generic Type for Abstract Config Handler
- Fixed an issue where TreeMap was not comparing correctly, creating inconsistent behaviors with the onStateLoad/Change handlers
All Test Cases.
These changes are required for a successful upgrade to 1.1.0.M2

Milestone Release Readiness Changes

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/MessageConditional.java

Added Javadoc changes for `MessageConditional`
N/A
I mostly just read it.
N/A

Documentation Update

---

nimbus-ui/nimbusui/src/app/components/platform/form.component.ts
nimbus-ui/nimbusui/src/app/components/platform/header/header-global.component.html

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Include a bulleted list of high level changes here.

update classes for Bootstrap and small screen responsive header nav

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/package.json
nimbus-ui/nimbusui/src/app/app.module.ts
nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.ts
nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.html
nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.ts
nimbus-ui/nimbusui/src/app/shared/grid-utils.ts
nimbus-ui/nimbusui/src/app/shared/param-annotations.enum.ts
nimbus-ui/nimbusui/src/app/shared/param-state.ts
nimbus-ui/nimbusui/src/app/shared/param-utils.ts

Merge TreeGrid Changes
- Added Card Grid Details to Accordion
- Element Id logic for nested collections.
Unit test cases on UI rerun

M2 treegrid

---

nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.html
nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Include a bulleted list of high level changes here.

added additional check

---

nimbus-ui/nimbusui/src/app/components/platform/fileupload/file-upload.component.ts
nimbus-ui/nimbusui/src/app/shared/message.ts

Fixing an issue where inline messages were not using the configured `styleClass` attribute in configuration.
Fixes NIM-18860
- Adding styleClass as an attribute to message, so it is correctly generated and displayed from `form.component.ts`
Functional Testing
N/A

NIM-18860: Message styles not correct

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/WebConfig.java
pom.xml

Resolve the existing duplications reported via Sonar.
Fixes NIM-17257: Fix Duplications
- Include a bulleted list of high level changes here.
Sonar and Test Cases
N/A

NIM-17257: SONAR - Fix Duplications

---

nimbus-ui/nimbusui/src/app/services/page.service.ts

Breadcrumb label conditional is not working as expected
Fixes # 18938
- Processed the update of the page and it was currently missed. We were processing only the nested params.

breadcrumb label conditional fix

---

nimbus-ui/nimbusui/src/app/components/platform/form-element.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/calendar.component.ts
nimbus-ui/nimbusui/src/app/shared/validationconstraints.enum.ts

Validation messages for form controls are duplicated.
Fixes # 19184
- Refactored the validation messages

validation messages refactor + message fix

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/services/layout.service.spec.ts
nimbus-ui/nimbusui/src/app/services/layout.service.ts
nimbus-ui/nimbusui/src/app/services/page.service.ts
nimbus-ui/nimbusui/src/app/shared/param-annotations.enum.ts

Support for images on the header of the submenu panel. 
Fixes # 18906
- Removed the @Section(Type.MENUPANEL) and replaced with @MenuPanel, that supports img-src.
UI Change

support for icons in panel submenu header

---

README.md
nimbus-starter/pom.xml
pom.xml

Merging Web Teks updates for Nexus release artifact build into latest.

Merge Nexus Updates into Latest

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java

Updating javadocs for applyValueStyles
- Javadoc update
None.
None.

Updating javadocs for applyValueStyles

---

.github/pull_request_template.md

Updating the pull request template.

Updating pull request template

---

nimbus-ui/nimbusui/e2e/home-page/home.po.ts
nimbus-ui/nimbusui/src/app/components/platform/panelmenu.component.ts
nimbus-ui/nimbusui/src/app/services/layout.service.ts
nimbus-ui/nimbusui/src/app/shared/menuitem.ts

Please review the following changes.

Updated e2e test cases and panel menu id 

---

nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.ts
nimbus-ui/nimbusui/src/app/services/page.service.ts

Null check was missing for nested collection updates such as for a grid row.
Fixes # NIM-19995
- Added a null check

null check for nested collection updates

---

nimbus-ui/pom.xml
pom.xml

Updated the maven profile "run-ui-tests"
- Removed maven-karma-plugin as ui unit test cases need to run using angular CLI command.
- Added exec-maven-plugin to run the CLI command for UI test cases.
- Tested using "mvn test -P run-ui-tests" command.

Updated the maven profile "run-ui-tests"

---

nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form-element.component.html
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.html
nimbus-ui/nimbusui/src/app/components/platform/link.component.ts
nimbus-ui/nimbusui/src/app/shared/param-annotations.enum.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Include a bulleted list of high level changes here.

External pdf Link support

---

nimbus-core/pom.xml
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/ParamConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/support/DefaultJsonParamConfigSerializer.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/support/DefaultJsonModelSerializer.java
nimbus-entity-dsl/pom.xml
nimbus-extn-activiti/pom.xml
nimbus-starter/pom.xml
nimbus-test/pom.xml
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/defn/IgnoreTest.java
nimbus-ui/nimbusui/package.json
nimbus-ui/nimbusui/src/app/components/platform/form.component.html
nimbus-ui/nimbusui/src/app/components/platform/panelmenu.component.ts
nimbus-ui/nimbusui/src/app/services/page.service.ts
nimbus-ui/pom.xml
pom.xml

Merging 1.1.8 into 1.1.x
N/A
N/A
N/A

Merging 1.1.8 into 1.1.x

---

nimbus-ui/nimbusui/src/app/components/platform/base-element.component.ts
nimbus-ui/nimbusui/src/app/components/platform/base-label.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/base-control.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/input-label.component.ts
nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.html
nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.ts
nimbus-ui/nimbusui/src/app/shared/param-utils.ts

- Fixed an issue where `@LabelConditional` was not working for `@Modal` components.
- Added `nm-input-label` to `@Modal` template.
- Refactored duplicated code
- Functional testing in petclinic
N/A

Adding Dynamic Label Support for @Modal

---

nimbus-ui/nimbusui/src/app/app.module.ts

Bugfix: Missed file in previous commit
N/A
N/A
N/A

Adding missed file in app.module.ts

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorGet.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts

Table Column Style Override with cssClass.
@GridColumn to support cssClass for override.
Throw InvalidConfigException if a _get call is received without a refId
Tested using LTSS application
N/A

Table Column style override Capability. 

---

nimbus-ui/nimbusui/src/app/components/platform/form-error-message.component.ts

Changed the message of the counter component based on the new requirement.
UI Change
N/A
N/A
N/A
N/A

NIM-20529 counter message update

---

nimbus-ui/nimbusui/src/app/services/page.service.ts

CardDetailGrid is not showing up when cardDetail row body has a fieldvalue group in certain situations. 
Included a check for the path while accepting the updates for card detail grid.
N/A
N/A
N/A
N/A

bugfix - carddetail grid not showing up with fieldvaluegroup + Modals freezing due to core update

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValuesConditionalStateEventHandler.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/core/SampleCoreValuesEntity.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/ValuesConditionalStateEventHandlerIntegTest.java
nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.html

Adding a commit added in 1.1.x missed in 1.1.9 for @ValuesConditional support for enum types.
N/A
N/A
N/A
N/A

Support for @ValuesConditional and non-string types

---

nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts

Fixes an UI exception throw when deleting elements from a grid.
N/A
Functional Testing
N/A

Null safety check

---

nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.html
nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.ts

PrimeNG modal component changes introduced bugs in the application. 
Added a new lifecycle hook to calculate the modal size.
N/A
N/A

fix for no scrolbar on modal due to primeng code change

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/DefaultParamValuesHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/support/DefaultLoggingInterceptor.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s7/view/S7V_ViewMain.java

1. resolves @Values url relative to root command. 
2. adds command exec id (unique id) for loggin interceptor to help indentify input/output of commands that contain sub commands

optimizations to support product configuration

---

nimbus-ui/nimbusui/src/app/directives/print.directive.ts

- Fixes an issue where a UI console error would come related to print directive in some components.
- Null/Undefined safety check
Functional Testing
N/A

Unsubscribing from print directive only when necessary

---

nimbus-ui/nimbusui/package.json

Setting PrimeNG version to `6.1.5` as latest version due to this bug introduced in `6.1.6`:
https://github.com/primefaces/primeng/issues/6851
- Updated `package.json`
N/A
N/A

Set PrimeNG version

---

nimbus-core/lombok.config

Description
Cherry picking commit from 1.1.x into 1.1.10
https://github.com/openanthem/nimbus-core/pull/282
N/A
N/A
N/A
N/A

cherry-picking 1.1.x commit for adding lombok.config into 1.1.10

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/button.component.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.ts

Missed checkin for button to have event propagation directive and modal was moving in some occasions making the usability hard.
added timeout to run outside of angular's change detection to reposition the overlay. 
added the event propagation directive to the button.
N/A
N/A
N/A
N/A

event propagation on button + modal fix for random moving

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/button.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/event-propagation.directive.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts

Refactored button and event propagation directive 
N/A
N/A
N/A

clean up of button, eventpropagation + table postbuttonurl null fix

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java

- Documentation Update
- Documentation Update
N/A
N/A

Documentation Updates

---

nimbus-core/lombok.config

Cherry picking commit from 1.1.x into 1.1.9-RC2
https://github.com/openanthem/nimbus-core/pull/282

cherry-picking 1.1.x commit for adding lombok.config into 1.1.9-RC2

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/search/DefaultSearchFunctionHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/search/DefaultSearchFunctionHandlerExample.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/search/DefaultSearchFunctionHandlerLookup.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/search/DefaultSearchFunctionHandlerQuery.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/db/SearchCriteria.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/core/SampleTask.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/VPSampleViewPageGreen.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorSearchHttpTest.java

- Added `orderBy`, `fetch`, and `aggregate` support to `DefaultSearchFunctionHandlerLookup`.
- Added `orderBy`, `fetch`, and `aggregate` support to `DefaultSearchFunctionHandlerLookup`.
- Polish
- DefaultActionExecutorSearchHttpTest#testLookupSort()
See http://discourse.oss.antheminc.com/t/how-to-sort-the-below-query-in-ascending-or-descending-order-alphabitical-for-combobox/379

NIM-20992, Lookup Search Improvements

---

nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.ts
nimbus-ui/nimbusui/src/app/components/domain/layout-resolver.service.ts
nimbus-ui/nimbusui/src/app/services/layout.service.ts

- Fixed an issue where layout components were not updating all of the time.
- Changed emitted object of `LayoutResolver` from type `string` to `ViewRoot`
- Functional Testing in client applications and Petclinic
N/A

NIM-21053: Fixes Layout Update Issue

---

nimbus-ui/nimbusui/package.json
nimbus-ui/nimbusui/src/app/components/platform/card/card-details-field-group.component.ts
nimbus-ui/nimbusui/src/app/components/platform/card/card-details-field.component.ts
nimbus-ui/nimbusui/src/app/components/platform/card/card-details.component.html
nimbus-ui/nimbusui/src/app/components/platform/card/card-details.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.html
nimbus-ui/nimbusui/src/app/components/platform/form-element.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form-group.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form.component.html
nimbus-ui/nimbusui/src/app/components/platform/form.component.ts
nimbus-ui/nimbusui/src/app/components/platform/section.component.html
nimbus-ui/nimbusui/src/app/components/platform/tile.component.html
nimbus-ui/nimbusui/src/app/components/platform/tile.component.ts

Bootstrap upgrade to use flexbox feature to handle form and carddetails layout.
N/A
Bootstrap upgrade
Tested via LTSS
N/A

flexbox styles

---

nimbus-ui/nimbusui/src/app/services/page.service.ts

- Fixed an issue where the `expandable` feature of `@Grid` was not working when navigating between pages
- Added safety check to ensure correct logic
- Functional testing in Petclinic
N/A

NIM-21231: Fixing @Grid expandable feature

---

nimbus-ui/nimbusui/src/app/components/platform/form-error-message.component.ts
nimbus-ui/nimbusui/src/app/components/platform/link.component.ts

Counter message in forms would consider other validations on the required fields. Links on grid would now support dynamic values. This was not working accurately earlier
Counter message directive and link component changes
N/A
N/A
pet clinic app
N/A
N/A

Counter message logic update + Link with dynamic value

---

nimbus-ui/nimbusui/src/app/components/platform/link.component.spec.ts

test case fix

---

nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.html
nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.spec.ts
nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.html
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.ts
nimbus-ui/nimbusui/src/app/services/page.service.spec.ts
nimbus-ui/nimbusui/src/app/services/page.service.ts

Support for setting messages at the domain level and refactored the error message display on UI. 
Domain component will show messages that are transient in nature. The error messages that were previously displayed at the page level are now shown at the domain component and they are also transient
A bug fix on accepting nested param updates
N/A

domain flow to support messages + error message refactor

---

nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form-group.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form-group.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/button-group.component.spec.ts

Created testcases scenarios

---

nimbus-ui/nimbusui/src/app/app.module.ts
nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.spec.ts
nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.ts
nimbus-ui/nimbusui/src/app/components/domain/layout-resolver.service.ts
nimbus-ui/nimbusui/src/app/components/platform/base-label.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/label.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.html
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts

Layout rendering issue fixed on refreshing app. Grid multiselect with filter causing expression changed after checked issue.
Resolver to emit domain object. 
Change detection called when value updates

NIM-21533, NIM-21534 & NIM-21352

---

nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.html
nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.ts

Overriding primeNG's attribute to support proper filtering.
N/A
N/A
N/A
N/A

Treegrid - filtering

---

.github/issue_template.md

* Adding an issue template
* Adding this to 1.1.x so it is propogated up to master as the issue template to use on all branches

Issue Template

---

nimbus-ui/nimbusui/src/app/components/platform/card/card-details-field-group.component.ts
nimbus-ui/nimbusui/src/app/components/platform/card/card-details.component.html
nimbus-ui/nimbusui/src/app/components/platform/content/accordion-tab.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.ts

Fix styling with Card Details. Account for FieldGrouping in Card Header.
Set Focus to Accordion when it becomes visible.
Fix styling with Card Details. Account for FieldGrouping in Card Header.
Set Focus to Accordion when it becomes visible.
Tested with Petclinic
N/A

NIMBUS-96:: Card Details Styles and Accordion focus on visible

---

nimbus-ui/nimbusui/src/app/components/platform/card/card-details-field-group.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.spec.ts

updated accordion.spec.ts and card-details-field-group.component.spec.ts

NIMBUS-96:: Updated accordion and card-details-field-group.component testcases

---

nimbus-ui/nimbusui/package.json
nimbus-ui/nimbusui/src/app/components/platform/form/elements/rich-text.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/rich-text.component.ts
nimbus-ui/nimbusui/src/app/mockdata/rich-text.component.mockdata.spec.ts

* Adds UI test cases for `@RichText`
N/A
N/A
* See `rich-text.component.spec.ts`
N/A

NIMBUS-10:: RichText Component (test cases)

---

nimbus-ui/nimbusui/src/app/components/platform/base-label.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/input-label.component.spec.ts

Updating the label was not reflecting in the UI. So, updated base-label-component.ts to fix it.
tested in petclinic application

Updated base-label.component.ts

---

nimbus-ui/nimbusui/src/app/components/platform/form-element.component.html
nimbus-ui/nimbusui/src/app/components/platform/form/elements/input-mask.component.ts
nimbus-ui/nimbusui/src/app/services/layout.service.ts

Access conditional for panel menus and sub-panel menus.
N/A
N/A
N/A
N/A

NIMBUS-114:: Access conditional for panel menus

---

.github/issue_template.md

* Added Issue Template
N/A
N/A
N/A
N/A

NIMBUS-42:: Issue Template

---

nimbus-ui/nimbusui/src/app/services/control-subscribers.service.ts
nimbus-ui/nimbusui/src/app/shared/param-state.ts

* Fixed an issue where `previousLeafState` was being stored correctly
* See code change
* Functional Testing in petclinic
* Test cases pending
N/A

NIMBUS-117:: PreviousLeafState fix

---

nimbus-ui/nimbusui/src/app/components/platform/link.component.ts

logout link defect
N/A
N/A
N/A
N/A

NIMBUS-21:: logout link defect

---

nimbus-ui/nimbusui/src/app/components/platform/tile.component.html

Fix bug with section style class
Fix bug with section style class
unit test cases
N/A

Section styles fix

---

nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts

NIMBUS-106:: Expanded row defect

---

nimbus-ui/nimbusui/src/app/components/platform/form-builder.service.spec.ts
nimbus-ui/nimbusui/src/app/mockdata/form-builder.service.mockdata.spec.ts
nimbus-ui/nimbusui/src/app/mockdata/index.ts
nimbus-ui/nimbusui/src/app/mockdata/layout.service.mockdata.spec.ts
nimbus-ui/nimbusui/src/app/services/layout.service.spec.ts

Updated services testcases and mockdata

NIMBUS-56:: Updated service testcases

---

nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.spec.ts
nimbus-ui/nimbusui/src/app/mockdata/table.component.mockdata.spec.ts

NIMBUS-106:: Expandable row test case.

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/search/DefaultSearchFunctionHandlerLookup.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/LabelStateEventHandler.java

* Minor code quality improvements
* Added a null safety check for `@Grid` label creation of a non complex entity.
* Code clean up related to Java 8 lambda
* (See`pvComparator`) This was causing a compile error on my machine. Not sure if updating my JDK would have fixed the issue, but it the change is appropriate.
* Existing test cases
N/A

Code Cleanup

---

nimbus-ui/nimbusui/package.json

Update SASS version to include the latest style fixes
N/A
Styles tested in Petclinic app.
N/A

Update Sass version

---

nimbus-ui/nimbusui/src/app/components/platform/card/card-details-field-group.component.ts
nimbus-ui/nimbusui/src/app/components/platform/card/card-details.component.html

Hide the field component when hidden attribute is set to false.
N/A
N/A
N/A

hidden attribute for card details field

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultCommandExecutorGateway.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultExecutionContextPathVariableResolver.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/Constants.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/app.module.ts
nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/content/tab.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form-element.component.html
nimbus-ui/nimbusui/src/app/components/platform/form-error-message.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form-group.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/autocomplete.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/autocomplete.component.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/section.component.html
nimbus-ui/nimbusui/src/app/components/platform/section.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/tile.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.spec.ts
nimbus-ui/nimbusui/src/app/mockdata/autocomplete.component.mockdata.spec.ts
nimbus-ui/nimbusui/src/app/services/autocomplete.service.ts
nimbus-ui/nimbusui/src/app/services/control-subscribers.service.ts
nimbus-ui/nimbusui/src/app/shared/param-annotations.enum.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts
nimbus-ui/nimbusui/src/app/shared/param-utils.ts

Autocomplete feature.
N/A
N/A
N/A
N/A

NIMBUS-16: Autocomplete feature

---

nimbus-ui/nimbusui/src/app/components/platform/base-element.component.ts
nimbus-ui/nimbusui/src/app/components/platform/card/card-details-grid.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/label.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form-element.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/signature.component.ts
nimbus-ui/nimbusui/src/app/components/platform/header/header-global.component.ts

* Fixes an issue where the form label was not being rendered in modals
* Refactored label size handling (for readability)
* removed unwanted `console.log` statements
N/A
N/A

NIMBUS-113: Fixing a form label issue

---

nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts

Search on a grid fails after export grid functionality
Created new object from the existing table to call the export function.

NIMBUS-139:: page urnresponsive on grid export

---

nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.html
nimbus-ui/nimbusui/src/app/components/platform/actiontray.component.ts
nimbus-ui/nimbusui/src/app/components/platform/card/card-details-field-group.component.ts
nimbus-ui/nimbusui/src/app/components/platform/card/card-details-field.component.html
nimbus-ui/nimbusui/src/app/components/platform/card/card-details-grid.component.html
nimbus-ui/nimbusui/src/app/components/platform/card/card-details.component.html
nimbus-ui/nimbusui/src/app/components/platform/content/accordion-tab.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.html
nimbus-ui/nimbusui/src/app/components/platform/content/tab.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form-element.component.html
nimbus-ui/nimbusui/src/app/components/platform/form-group.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form.component.html
nimbus-ui/nimbusui/src/app/components/platform/form/elements/action-dropdown.component.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.html
nimbus-ui/nimbusui/src/app/components/platform/header/header-global.component.html
nimbus-ui/nimbusui/src/app/components/platform/menu.component.ts
nimbus-ui/nimbusui/src/app/components/platform/section.component.html
nimbus-ui/nimbusui/src/app/components/platform/tile.component.html
nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.html

NIMBUS-166: Unique ids for UI components (needed for selenium tests)

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultFrameworkExtensionsConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/AbstractConfigEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/LabelStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/ToolTipStateEventHandler.java
nimbus-ui/nimbusui/src/app/app.module.ts
nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/card/card-details-field-group.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/card/card-details-field.component.html
nimbus-ui/nimbusui/src/app/components/platform/card/card-details-field.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/card/card-details-field.component.ts
nimbus-ui/nimbusui/src/app/components/platform/card/card-details-grid.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/charts/chart.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/content/tab.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form-error-message.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form-group.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/section.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/tile.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.spec.ts
nimbus-ui/nimbusui/src/app/shared/param-annotations.enum.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

NIMBUS-141: Tooltip

---

nimbus-ui/nimbusui/src/app/app.module.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/autocomplete.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/autocomplete.component.ts

NIMBUS-160: Autocomplete unit tests

---

nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/button-group.component.ts
nimbus-ui/nimbusui/src/app/components/platform/panelmenu.component.ts

NIMBUS-123: Unique ids

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/search/DefaultSearchFunctionHandlerLookup.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.html
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/services/httpclient.service.ts
nimbus-ui/nimbusui/src/app/services/page.service.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

Builds on top of the existing `@Grid` inline edit and pushes the data to the server.
* `@Grid` now supports inline-editing
* The attributes `addRow` and `editRow` have been added to enable each respective feature.
* The attributes `onAdd` and `onEdit` take a param path string on which the UI will invoke a `_get`call on when the respective action is performed.
* This allows the developer the ability to configure what should happen with the edited data via `@Config` or any other framework configurations.
N/A
N/A

 NIMBUS-171: grid inline edit 

---

nimbus-ui/nimbusui/src/app/components/platform/form-builder.service.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.constants.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.spec.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.ts
nimbus-ui/nimbusui/src/app/services/page.service.ts
nimbus-ui/nimbusui/src/app/shared/param-state.ts
nimbus-ui/nimbusui/src/app/shared/param-utils.ts

Refactors the underlying data transformation from param to `TableBasedData`. This change will hopefully provide for better maintainability of table based components going forward.
**Primary Changes**
* refactored the logic for building of grid data to `TableBasedData` and `RowData`
* removed duplicated grid data building logic from `page.service.ts`
* optimized transformation of `Param` to `TableBasedData`
**Semantic Changes**
* renamed `GridData.leafState` to `TableBasedData.values`
* renamed `Param.gridData` to `Param.tableBasedData`
* moved  `Param.collectionParams` to `Param.tableBasedData.collectionParams`
N/A
N/A

grid data refactor

---

README.md
hello-world
nimbus-core/src/main/java/com/antheminc/oss/nimbus/channel/web/WebActionController.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/ToolTipStateEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/AbstractListPaginatedParam.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/db/mongo/DefaultMongoModelPersistenceHandler.java

readme cleanup and sonar fixes
N/A
N/A
N/A
N/A

repo cleanup

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.html
nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.ts
nimbus-ui/nimbusui/src/app/components/home/home-layout.component.html
nimbus-ui/nimbusui/src/app/components/home/home-layout.component.ts
nimbus-ui/nimbusui/src/app/model/menu-meta.interface.ts
nimbus-ui/nimbusui/src/app/services/layout.service.ts

Fixes #456 
`@MenuPanel` now offers support for `align` with the following properties:
* `Align.DEFAULT`
* `Align.HORIZONTAL`
* `Align.VERTICAL`
* Changes model for the UI backing model of array to an object called `MenuPanel`.
N/A
N/A

NIMBUS-179: menu panel orientation control

---

nimbus-ui/nimbusui/src/app/app.module.ts
nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.html
nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.ts
nimbus-ui/nimbusui/src/app/components/home/home-layout.component.html
nimbus-ui/nimbusui/src/app/components/navigation/navigation.component.ts
nimbus-ui/nimbusui/src/app/model/menu-meta.interface.ts
nimbus-ui/nimbusui/src/app/services/layout.service.ts

Fixes #456
Fixes a styling/dom issue with the `@MenuPanel` when configured with `Align.HORIZONTAL`.
- Changes some styling around for the `@MenuPanel` configured with `Align.HORIZONTAL`.
- Refactored `withInfoBar` to use different class assignment directive.
- Moved some of the DOM structure of existing the "home" component to the domain-flow component
- Moved the structure of the `Align.HORIZTONAL` `@MenuPanel` outside of an unnecessary wrapper container.
N/A
N/A

panel menu/global nav changes

---

nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.ts

performance refactor: accordion tabinfo

---

nimbus-ui/nimbusui/src/app/components/domain/domain-flow.component.ts
nimbus-ui/nimbusui/src/app/components/platform/actiontray.component.ts
nimbus-ui/nimbusui/src/app/components/platform/base-element.component.ts
nimbus-ui/nimbusui/src/app/components/platform/base-label.component.ts
nimbus-ui/nimbusui/src/app/components/platform/breadcrumb/breadcrumb.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/page-content.component.ts
nimbus-ui/nimbusui/src/app/components/platform/fileupload/file-upload.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form-element.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/base-control.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/button.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/checkbox-group.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/filter-button.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/inplace-editor.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/input-label.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/multi-select-card.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/multi-select-listbox.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/picklist.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/signature.component.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/components/platform/header/header-global.component.ts
nimbus-ui/nimbusui/src/app/components/platform/modal/modal.component.ts
nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.ts
nimbus-ui/nimbusui/src/app/services/control-subscribers.service.ts
nimbus-ui/nimbusui/src/app/services/logger.service.ts
nimbus-ui/nimbusui/src/app/shared/param-state.ts

The changes made reduces the memory footprint of the application and also reduce the scripting time needed for page to render
All subscribers are unsubscribed when the component is destroyed. The counter message is evaluated only once per event/notify call.

NIMBUS-203 Nimbus-204: Performance improvements and efficient memory utilization

---

nimbus-ui/nimbusui/src/app/app.module.ts
nimbus-ui/nimbusui/src/app/components/platform/base-label.component.ts
nimbus-ui/nimbusui/src/app/components/platform/content/label.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/input-label.component.ts

Refactored label to evaluate css on initial load and when there is an update for the param
Move css to baselabel and required icon evaluation to html

label - evaluate css on events

---

nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/components/platform/validators/ValidationUtils.ts
nimbus-ui/nimbusui/src/app/components/platform/validators/custom.validators.ts
nimbus-ui/nimbusui/src/app/shared/validationconstraints.enum.ts

NIMBUS-202: Grid selection and Not empty validation

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultFrameworkExtensionsConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/TableBasedStateLoadEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/extension/TreeGridStateLoadHandler.java
nimbus-ui/nimbusui/src/app/components/platform/tree-grid/tree-grid.component.html
nimbus-ui/nimbusui/src/app/shared/param-state.ts

Fixed an issue where `@TreeGrid` and labels were not displaying due to latest refactor changes.
N/A
N/A
N/A

fixing treegrid labels not displaying

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/builder/internal/AbstractEntityConfigBuilder.java

Adds more descriptive error logging for when user configures something with two view config annotations:
```java
@Button
@ButtonGroup
private String p1;
```
Previously, the error log did not give field information. Now it would look as displayed below:
**Sample Error Log**
```
Caused by: com.antheminc.oss.nimbus.InvalidConfigException: [Ex-UID:{20190522-153649.746-0.878496848989468}] Failed to decorate uiStyles attribute for field "p1".
at ...
Caused by: com.antheminc.oss.nimbus.InvalidConfigException: [Ex-UID:{20190522-153649.746-0.8155825417073538}] Found more than one element of config: [AnnotationConfig(name=ViewConfig.Button, value=null, annotation=@com.antheminc.oss.nimbus.domain.defn.ViewConfig$Button(b=$execute, method=GET, browserBack=false, formReset=true, type=button, title=, …
```

providing more useful error log

---

nimbus-ui/nimbusui/src/app/app.module.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/base-control.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/textbox.component.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.html
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/directives/validateInput.directive.ts

Created validations in Table component for row edit and add features
Tested in pet clinic application

NIMBUS-183::Created validations in Table component

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/breadcrumb/breadcrumb.component.ts
nimbus-ui/nimbusui/src/app/components/platform/breadcrumb/breadcrumb.service.ts
nimbus-ui/nimbusui/src/app/components/platform/content/page-resolver.service.ts
nimbus-ui/nimbusui/src/app/services/layout.service.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

Enhanced breadcrumb to show the previously visited pages as per the flow.
Added query params to menu panel
Changed the bread crumb component
Added additional properties for page and menupanel annotations

NIMBUS-74: NIMBUS:78: Breadcrumb enhancement

---

nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/s11/FunctionExecutorTests.java

Fixing a broken test case
N/A
N/A
N/A
N/A

Fix for a broken test case

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/combobox.component.ts

combobox val selection fix due to primeng upgrade

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/combobox.component.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts

Includes bugfixes made in 1.3.1.M1 for merging into 1.3.x
* 70cc13a2156f416fec436e9b495dc7cc7bb0c953
* 77d55331683e643cdc7ec45da6bc05d6e9e99443

bugfix merges from 1.3.1.M1

---

nimbus-ui/nimbusui/package.json

Fixes #520, #521 
Fixed a regression bug `@GridColumn` element text was not wrapping (See style fix for: [c21d6d7](https://github.com/openanthem/nimbus-sass-module/commit/c21d6d7cce5b04c018bd4c5bb938750756477488))
* Bumped nimbus-sass-module version in accordance with css change.

NIMBUS:: 233, 234 Fix for GridColumn wordwrap

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/calendar.component.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.constants.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.html

* Adds support for `@Calendar` when using the `editRow` feature of `@Grid`.
N/A

NIMBUS-232: Row Edit (calendar)

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/picklist.component.ts

Fixes #487
Fixed an issue where `@Picklist` was giving a UI console error.
* Null safety check and correct value mapping
N/A

NIMBUS-211

---

nimbus-ui/nimbusui/src/app/components/platform/breadcrumb/breadcrumb.component.ts

Fixes #527 
Fixes an issue where breadcrumb was not generating submenu items
N/A
N/A

NIMBUS-238: breadcrumb

---

nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.html
nimbus-ui/nimbusui/src/app/services/page.service.ts
nimbus-ui/nimbusui/src/app/shared/param-state.ts

Fixes #540 
Fixes an issue where removing `@Grid` line items was throwing a browser console error.
N/A
N/A
N/A

NIMBUS-245: @Grid dynamic removal fix

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.html
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/components/platform/loader/loader.component.ts
nimbus-ui/nimbusui/src/app/components/platform/loader/loader.state.ts
nimbus-ui/nimbusui/src/app/services/loader.service.ts
nimbus-ui/nimbusui/src/app/services/page.service.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

Grid loads were not showing the loader icon in some use cases
Grid will always show a custom loader icon until the data refresh is done.

NIMBUS-225: grid custom spinner icon

---

nimbus-ui/nimbusui/package.json

Fixes #544, @CardDetail in @GridRowBody text wrapping issue.
* Updated the styling
```
```
Functional testing in Petclinic
N/A

NIMBUS-248: text wrapping issue for @Grid

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/BPMEngineConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/bpm/activiti/ActivitiBPMGateway.java

Reverts openanthem/nimbus-core#538

Revert "NIMBUS-135: Active Task Synch Issue"

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/picklist.component.ts

Fixes #547 
* Simplified state setting logic that appears to be no longer needed
* Removed drag and drop code, it isn't necessary since PrimeNG supports it out of the box.
N/A

NIMBUS-253: fixing picklist state issue

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/header-checkbox.component.ts

Select All functionality is not working when the user navigates from page1 to page 2 on server side paginated grid

NIMBUS-261: selectall fix for serverside pagination

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultExecutionContextPathVariableResolver.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s0/view/SampleCoreEntityAccessLineItem.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorSearchHttpTest.java

Grid filter does not work with ZonedDateTime fields on server
Added support for ZoneDateTime fields on server side grids
N/A
t06_GridZoneDateTimeFilter()

NIMBUS-249: filter support for ZonedDateTime

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/ParamStateRepositoryGateway.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/AuditStateChangeHandlerTest.java

Changed the _equals method for array
added the condition to compare array values 
audit_arrayType

array equals change

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/AbstractCommandExecutor.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorNew.java

Test case fixes for FileImporter tests

NIMBUS-200: Fixing test cases

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/RuleSet.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/ValidationRule.java
nimbus-ui/nimbusui/package.json
nimbus-ui/nimbusui/src/app/components/platform/form-builder.service.ts
nimbus-ui/nimbusui/src/app/components/platform/form.component.html
nimbus-ui/nimbusui/src/app/components/platform/form.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/multi-select-listbox.component.ts
nimbus-ui/nimbusui/src/app/components/platform/validators/ValidationUtils.ts
nimbus-ui/nimbusui/src/app/components/platform/validators/custom.validators.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts
nimbus-ui/nimbusui/src/app/shared/validationconstraints.enum.ts

Ability to evaluate certain rules on client side.
Introduced new annotation @ValidationRule to evaluate certain rules on the client side and show appropriate error messages that are configured. The form cannot be submitted until the rules are satisfied.

NIMBUS-210: validation rule changes + multiselect clean up

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/EntityState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/StateHolder.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/AuditStateChangeHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ChangeLogCommandEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultParamState.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/entity/audit/AuditEntry.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/domain/mock/MockParam.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/model/state/extension/AuditStateChangeHandlerTest.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/changelog/ChangeLogTest.java

Fixes #569
Added previousLeafState to `Param`
* See `ChangeLogTest`
* See existing Audit test cases
N/A

NIMBUS-273: ChangeLog - Persist previous value along with changed value

---

nimbus-ui/nimbusui/src/app/services/control-subscribers.service.ts
nimbus-ui/nimbusui/src/app/shared/param-utils.ts

THIS IS A WIP
Fixes #585 
N/A
N/A
N/A

[WIP] NIMBUS-280: UI Date refactor

---

nimbus-ui/nimbusui/src/app/components/platform/content/accordion.component.ts

Support of initialization calls for accordion and accordion tab
Support added in accordion component to make an http call on initialization

NIMBUS-279: accordion - support of initialize config call

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/WebConfig.java
nimbus-ui/nimbusui/package.json
nimbus-ui/nimbusui/src/app/components/platform/form-builder.service.ts
nimbus-ui/nimbusui/src/app/components/platform/form.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/button.component.ts
nimbus-ui/nimbusui/src/app/services/control-subscribers.service.ts
nimbus-ui/nimbusui/src/app/services/page.service.ts
nimbus-ui/nimbusui/src/app/shared/param-state.ts
nimbus-ui/nimbusui/src/app/shared/param-utils.ts

Fixes #585 and #591
* Adding back previous date fix commits with a few modifications
* Converted the form component's `FormGroup` to a `NimbusFormGroup` to pass along the `ParamConfig` objects for each form element in the form group.
* `button.component.ts` now correctly parses the config codes to determine the date datatype and how it should be converted before sending back to the server.
* Fixed an issue where server was not deserializing the `ZonedDateTime` time zones correctly.
* Fixed a non-breaking console error related to a previous form validation message change.
N/A
N/A

[WIP] NIMBUS-280: Date and minor error fix

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java

Adds missing documentation
* Javadoc explanation for `@Accordion`, `@AccordionTab`
N/A
N/A

Documentation update: @Accordion, @AccordionTab

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultCoreBuilderConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultCoreConfiguration.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultMongoConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultCommandExecutorGateway.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/extension/ChangeLogCommandEventHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/DefaultStateEventDelegator.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/test/scenarios/multidb/MultipleMongoConfig.java

Fixes #604 
* Made the `ChangeLog` event handler an optional bean
* If RDBMS is configured, a ChangeLog event handler bean is not created
* temporary - _ChangeLog with RDBMS has some issues currently_
N/A
N/A

NIMBUS-297: @ChangeLog ModelRepository abstraction

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/textbox.component.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

Ability to configure autofill feature from browser. Disabled by default
Added autocomplete feature to textbox

configurable autofill

---

nimbus-ui/nimbusui/package.json
nimbus-ui/nimbusui/src/index.html

Change to include branding styles
Company specific styles can be loaded followed by app specific overrides

brand styles

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/entity/person/Address.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/entity/person/Name.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/entity/person/Person.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/entity/person/Phone.java

Fixes #609. 
* Added `AllArgsConstructor` and `NoArgsConstructor` to commonly used native domain entities.
N/A
N/A

NIMBUS-300: AllArgsConstructor for native Domain Entities

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/action-dropdown.component.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

Link menu will be collapsed on selecting a link when the user configures the collapseOnClick property on link menu.
action drop component has an event listener on the child component links.

NIMBUS-299: collapse linkmenu on selecting link

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/RuleSet.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/ValidationRule.java

Documentation for `@ValidationRule` and `@RuleSet`
* Javadoc update
N/A
N/A

ValidationRule javadocs

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultCoreConfiguration.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultMongoConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/channel/web/WebActionController.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/FileUploadStrategy.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/RuleSet.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/extension/ValidationRule.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/entity/fileUpload/FileAttributes.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/entity/fileUpload/FileHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/entity/fileUpload/FileUploadMongo.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/entity/fileUpload/FileUploadService.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/entity/fileupload/FileUploadTest.java
nimbus-ui/nimbusui/src/app/components/platform/fileupload/file-upload.component.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/action-dropdown.component.ts
nimbus-ui/nimbusui/src/app/services/file.service.ts
nimbus-ui/nimbusui/src/app/shared/param-annotations.enum.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

The change is to incorporate File Upload and Download Functionality as part of the framework.
https://anthemopensource.atlassian.net/browse/NIMBUS-307
Changes in WebActionController to open up file upload/download
Changes to include File Upload Handler so that strategy for upload/download as in which service to use is defined by the application thats using the service.
Changes in file-Upload Component to differentiate between external and internal links
Changes in file service to post all the metadata (and not just the metadata attribute ) thats posted as part of upload control.
Changes in action-dropdown component to add another link Type - Download.
[ ] New feature
[ ] This change requires a documentation update
N/A
Test Case added for Nimbus Core and petclinic app
N/A
N/A

1.3.x.file upload

---

nimbus-ui/nimbusui/package.json

Calendar pop up gets closed on selecting the month from the pop up.

primeng 7.1.3 upgrade

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/session/HttpSessionProvider.java

null check

---

nimbus-ui/nimbusui/src/app/components/platform/form/elements/button.component.ts

Loader icon does not appear when the file is being uploaded to an external repository.
Added the loader icon in the file upload component.
N/A

NIMBUS-388 :: load icon on file upload

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/src/app/components/platform/form/elements/textbox.component.ts
nimbus-ui/nimbusui/src/app/shared/param-annotations.enum.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

Ability to configure to post once after a certain character count limit or post on reaching certain character count on textbox.
@TextBox(postEventOnChange=true, inputEvent = {@InputEvent(eventType = EventType.INPUT, charCountToPostOnce = 1)})
@TextBox(postEventOnChange=true, inputEvent = {@InputEvent(eventType = EventType.INPUT, count = 1)})

NIMBUS-387 :: Feature/inputevent

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/ViewConfig.java
nimbus-ui/nimbusui/package.json
nimbus-ui/nimbusui/src/app/app.module.ts
nimbus-ui/nimbusui/src/app/components/platform/form/elements/textbox.component.ts
nimbus-ui/nimbusui/src/app/pipes/mask.pipe.ts
nimbus-ui/nimbusui/src/app/shared/param-config.ts

mask all characters in textbox except the last few characters mentioned in the maskcount configuration.
@TextBox(postEventOnChange=true, maskcount =4, maskchar="*")
The above would mask all characters in the text box with '*' except the last 4.

NIMBUS-397 :: masking sensitive info + textbox

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/app/extension/config/DefaultCoreExecutorConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/AbstractCommandExecutor.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorGet.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorNew.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultActionExecutorSave.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/DefaultCommandPathVariableResolver.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/EntityLockHandler.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/Constants.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/defn/Lock.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/ModelConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/builder/internal/AbstractEntityConfigBuilder.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/config/internal/DefaultModelConfig.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/internal/ExecutionEntity.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/ExternalModelRepository.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/ModelRepository.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/db/mongo/DefaultMongoModelRepository.java
nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/model/state/repo/ws/DefaultWSModelRepository.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/FrameworkIntegrationTestScenariosApplication.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/domain/session/TestSessionProvider.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s15/core/LockEntry.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s15/core/LockView.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s15/core/SampleLockedEntity.java
nimbus-test/src/main/java/com/antheminc/oss/nimbus/test/scenarios/s15/core/TestLockUtils.java
nimbus-test/src/test/java/com/antheminc/oss/nimbus/domain/cmd/exec/internal/EntityLockingTests.java

Ability to Lock domain entities
@lock annotation added with alias and hooks to run configs at before locking, after locking and on failed locking.
EntityLockingTests

NIMBUS-374 :: Lock domain entity #667

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/domain/bpm/activiti/ActivitiBPMGateway.java

NIMBUS-394 :: Application Support (Merge M6 changes to M7)

---

nimbus-ui/nimbusui/src/app/components/platform/content/page-resolver.service.ts

ui event on redirection

---

nimbus-ui/nimbusui/src/app/app.module.ts
nimbus-ui/nimbusui/src/app/components/home/home-layout.component.ts
nimbus-ui/nimbusui/src/app/services/layout.service.ts

Ability to refresh components in layout when updates are received
Registered event listener to process the updates in the layout service

NIMBUS-393 :: handle layout updates

---

nimbus-core/src/main/java/com/antheminc/oss/nimbus/support/JustLogit.java

Special characters are logged
Added the '\\' character that was missed

NIMBUS-398 :: special character list updated

---

nimbus-ui/nimbusui/src/app/services/page.service.ts

Grid links are not showing in a few scenarios.
Added condition to deserialize the inner grid json values

NIMBUS-404, NIMBUS-405 :: Links not shown in grid

---

nimbus-ui/nimbusui/src/app/components/platform/form-builder.service.ts
nimbus-ui/nimbusui/src/app/components/platform/grid/table.component.ts
nimbus-ui/nimbusui/src/app/pipes/mask.pipe.ts

0 is not displayed in control such as grid, textbox
added null condition for value accessor

NIMBUS-415 :: 0 not displayed in controls
